### ISSUE TITLE
Unable to compile program

### ISSUE THREAD

**Issue by silkPK** [sourgrasses/crystal-oracle#1]
After installation a simple program like

` 
require "db"
require "oracle"

DB.open "oracle://user:password@host:port/SID" 
`

return the error

/usr/bin/ld: cannot find -lodpic (this usually means you need to install the development package for libodpic)
collect2: error: ld returned 1 exit status
Error: execution of command failed with code: 1: `cc "${@}" -o /home/ubuntu/snap/crystal/common/.cache/crystal/crystal-run-testOracle.tmp  -rdynamic -L/snap/crystal/1064/bin/../lib/crystal -lodpic -lpcre -lm -lgc -lpthread -levent -lrt -ldl`

**Comment by sourgrasses** [comment]
a) I stopped working on this around two years ago when I no longer had any need to write software to connect to Oracle databases, so this shard doesn't actually work.
b) Before opening an issue on a repo, you should consider just doing what the error message suggests or at least googling it. The linker wants you to install ODPI-C.

**Comment by silkPK** [comment]
Ok thanks.

The problem is that I have already installed ODPI-C.

Thank you for your work!
